lb_payment:
    resource: "@LBPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

lb_media:
    resource: "@LBMediaBundle/Controller/"
    type:     annotation
    prefix:   /

lb_notification:
    resource: "@LBNotificationBundle/Controller/"
    type:     annotation
    prefix:   /

lb_user:
    resource: "@LBUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /hwi_login

facebook_login:
    path: /login/check-facebook

twitter_login:
    path: /login/check-twitter

instagram_login:
    path: /login/check-instagram


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

main_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\MainController

new_report:
    type:     rest
    resource: AppBundle\Controller\Rest\ReportController

interest_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\InterestController

ad_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\AdController

group_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\GroupController

comment_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\CommentController


payment_rest:
    type:     rest
    resource: LB\PaymentBundle\Controller\Rest\PaymentController


tag_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\TagController

message_routing:
    resource: "@LBMessageBundle/Resources/config/routing.yml"

notification_routing:
    resource: "@LBNotificationBundle/Resources/config/routing.yml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

    
#    for lsoft ad
lsoft_ads:
    resource: "@LSoftAdBundle/Controller/"
    type:     annotation
    prefix:   /