<?php

namespace AppBundle\Entity\Repository;

/**
 * InterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $interestIds
     * @return array
     */
    public function findByIds($interestIds)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT i
                           FROM AppBundle:Interest i
                           WHERE i.id IN (:ids)")
            ->setParameter('ids', $interestIds)
            ->getResult();
    }

    /**
     * This function is used to get interest ids by user
     *
     * @param $userId
     * @return array
     */
    public function findIdsByUser($userId)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT i.id
                           FROM AppBundle:Interest i
                           JOIN LBUserBundle:User u WITH u.id = :userId
                           JOIN u.interests ui
                           WHERE  ui.id = i.id
                           ")
            ->setParameter('userId', $userId)
            ->getResult();
    }


    /**
     * This function is used to get interest ids by user
     *
     * @param $name
     * @return array
     */
    public function findByName($name)
    {
        $name = str_replace('"','', $name);

        return $this->getEntityManager()
            ->createQuery("SELECT i
                           FROM AppBundle:Interest i
                           WHERE  i.name = :name
                           ")
            ->setParameter('name', $name)
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

}
