<?php

namespace AppBundle\Entity\Repository;

/**
 * InterestGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findMaxMinPositions()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT MAX(ig.position) as maxPos, MIN(ig.position) as minPos
                           FROM AppBundle:InterestGroup ig")
            ->getSingleResult();
    }

    /**
     * @return array
     */
    public function findAllOrderByPosition()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT ig, i
                           FROM AppBundle:InterestGroup ig
                           JOIN ig.interest i
                           ORDER BY ig.position, i.position")
            ->getResult();
    }

    /**
     * @param $user
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */

    public function findGroupByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT g.name
                           FROM AppBundle:InterestGroup g
                           JOIN g.interest i
                           JOIN LBUserBundle:User ur WITH ur.id = :user
                           LEFT JOIN ur.interests ui
                           WHERE ui.id = i.id")
            ->setParameter('user', $user)
            ->getArrayResult();
    }

    /**
     * This function is used to interest by user id
     *
     * @param $userId
     * @return array
     */
    public function findAllByUser($userId)
    {
        $userId = 1;
        return $this->getEntityManager()
            ->createQuery("SELECT ig, i
                           FROM AppBundle:InterestGroup ig
                           JOIN ig.interest i
                           JOIN LBUserBundle:User ur WITH ur.id = :userId
                           LEFT JOIN ur.interests ui
                            WHERE ui.id = i.id
                           ORDER BY ig.position, i.position")
            ->setParameter('userId', $userId)
            ->getResult();
    }
}
