<?php

namespace AppBundle\Entity\Repository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     *
     */
    public function findAllWithAbbr()
    {
        $query =  $this->getEntityManager()
            ->createQuery("
                            SELECT s.abbr, s.name
                            FROM AppBundle:State s
                            INDEX BY s.abbr
                            ORDER BY s.name
                        ")
            ->getResult();

        // get names
        $result = array_map(function ($item){return $item['name'];}, $query);

        return $result;
    }

}
