<?php

namespace LB\PaymentBundle\Entity\Repository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     */
    public function findSubscriberStripId()
    {
        $results =  $this->getEntityManager()
            ->createQuery("SELECT s.stripeId
                       FROM LBPaymentBundle:Subscriber s
                       ")
            ->getResult();

        $results = array_map(function($result){return $result['stripeId'];}, $results);

        return $results;

    }

    /**
     * @return mixed
     */
    public function findAllSubscribers()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT s
                       FROM LBPaymentBundle:Subscriber s
                       INDEX BY s.stripeId
                       WHERE s.hide != true
                       ")
            ->getResult();
    }

    /**
     * @param $search
     * @return array
     */
    public function findAllForSelect2($search)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT s.id as id, s.stripeId as text
 							FROM LBPaymentBundle:Subscriber s
 							WHERE s.stripeId LIKE :search
                            ")
            ->setParameter('search', '%' . $search . '%')
            ->getResult();
    }
}
