lb_message:
    resource: "@LBMessageBundle/Controller/"
    type:     annotation
    prefix:   /

lb_messages_rest:
    resource: LB\MessageBundle\Controller\Rest\MessageController
    type:     rest
